### ISSUE TITLE
Doesn't compile when printing std::unordered_set

### ISSUE THREAD

**Issue by ncihnegn** [p-ranav/pprint#8]
This test case can't compile w/ Apple clang version 11.0.0 or gcc 8.3.0.
```
TEST_CASE("Print empty set (line_terminator = '\n', indent = 2)",
	  "[std::unordered_set]") {
  std::unordered_set<int> foo {};

  std::stringstream stream;
  pprint::PrettyPrinter printer(stream);
  printer.print(foo);

  const std::string expected = "{}\n";

  REQUIRE(stream.str() == expected);
}
```

**Comment by dingxiong** [comment]
This is because the implementation uses `std::prev` for set like containers. `std::prev` can only take bidirectional iterators. While set like container only has forward iterator. 
See https://stackoverflow.com/questions/23868378/why-stdprev-does-not-fire-an-error-with-an-iterator-of-stdunordered-set
I think using a count variable can easily fix this issue.
